apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:0coYOAfxxPiapaH4BKUYdCPNjAYwLT6RNBxtSrNPQq1YF/FSKA==,iv:Yt5oS1MFD6ySC+FYc0eJsjqKOTpMp3qr6Obv1gmZUlQ=,tag:xA5byKe+3WbWKKiRotd+fQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d9475twhfwhwymj2vzr6tgg7k8yfax3ag20nqgxusg2ppace5qeskeu4l5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6R3A5S3FpdGUySDE0SXdL
            QlFJNTRJenlPcXJldmtSRUNXUXpZMW5OdkVZCm1SSWVHMEpCQTdJRTNFV2E0NmpF
            QmxYQXBhSGxTaU5yRkJZdUhJdDVTbDAKLS0tIG9CN3RXekd1MVB3Rjh6UjZZM09U
            eHREQXUwNUZNMDFmUk84d2N4c0gvb2cKIi4THDFbAy7YbVAps5EqDnR1zfCKPc38
            N+LWe5IRCNOQRE7yWwxD+do9Qhpy4CQL9PLdh7vHnBqGcQuhQwGFSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-14T14:16:12Z"
    mac: ENC[AES256_GCM,data:Ls38GBBYyJzMkbgePe9NwlL691nkX8vvtnXNMv+EjK0WHCmg8BtFXDzc/vdQBKX/m75hGm9ALqGseyCOK3+gQ06maaShOcMmyTl++PF8XoHz7m9HbqTkvrDocJDhDSU1K6M2NZ7KjBHSKXGWJ3Fp5epOfzT6EJhr7J2hzsN4z+Y=,iv:xLvFmZYny0L/5JgY68OjNMTTdWwzGFP5KmRdNg701bQ=,tag:u7TvnnilUIJ5ePxS0Iv8Gg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
