apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:9gbCiiQ7lWZI5FlFaDIoSbUf,iv:r72UdQ5wakAzUKGwaduqx8xuI6q9pRMsPEl6upApEBw=,tag:12cwNEPGGQ4vBt2RZ5WIWw==,type:str]
    api-key: ENC[AES256_GCM,data:LaB3kFNjhlz9rQRbzzz9pBsR/CuXc6V4fdM5D6N0bBxmwUl5lw==,iv:C3DHMyr+pVP6iC3WgzglWcB5dwlWiMV34OK91YZ7zrk=,tag:ItanzUGYe6B2nzqaQ2KDAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d9475twhfwhwymj2vzr6tgg7k8yfax3ag20nqgxusg2ppace5qeskeu4l5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxNXQzb2FXQTkwM01KQmpy
            WGhEMStDMHFjK29XOUVpNFE1amw5RW8xb0FRClVWNFRManRKVzZ4dm92RzZ5V2wy
            NU5aOG96Nk5FMHlHV0cwQzVaRkJoeGcKLS0tIGkwSXhCcXZ4YlJZdlRwVGlmZHkx
            U0dXM21UYk9JMjBqQjloem1KTGVlQ1EK8gmttVLXaM5kmwXOuF3dAJjOW8pl4ztt
            8+w6a0xCGtntzUt7hjboiP9Y/TwuPGS4+rZfCgqg5/yaeJeuWkMcTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-14T14:16:12Z"
    mac: ENC[AES256_GCM,data:fX73Abmqo1EcsNN/bnbo9rtOuQl30kZ4WZWiNk7K7FOUAJ1UvRD3GqAH5RN/J5QwC1yhBUa3jskUpK5drBpNqpMWQ3WDHgSZlooloUewAiT29X2xgs3jdL+HusELDZUxcqnWFNNl9OU9BZN8vkMjBtcJ/gRgnfpvD/pbpvh89Dk=,iv:DTbCDp1upK2R4Xe0AREwJeBq5AAi1ETw8Nfgegi5qC0=,tag:yEBu8qugci9w5G78HaDPfg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
