---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Asia/Singapore"
  KUBE_VIP_ADDR: "10.100.100.254"
  METALLB_LB_RANGE: "10.100.100.200-10.100.100.210"
  METALLB_K8S_GATEWAY_ADDR: "10.100.100.201"
  METALLB_INGRESS_ADDR: "10.100.100.202"
